### ISSUE TITLE
digest.rb: library not found for class Digest::SHA512

### ISSUE THREAD

**Issue by zzak** [ruby/openssl#53]
```
/opt/ruby/ruby-2.3.1/lib/ruby/2.3.0/digest.rb:16:
in `const_missing': library not found for class Digest::SHA512 -- digest/sha2.so (LoadError)
```

This happens on all the [builds](https://travis-ci.org/ruby/openssl/builds/136202548)

**Comment by hsbt** [comment]
I can reproduce it on my docker env with zzak/ruby-openssl-docker.

**Comment by rhenium** [comment]
It looks like digest/sha2.so is incorrectly linked against libcrypto.so.1.1.

~~~
root@1b3ffd278d00:/home/openssl/code# ldd /opt/ruby/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/digest/sha2.so 
	linux-vdso.so.1 =>  (0x00007ffe9a38b000)
	libcrypto.so.1.1 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbfe88b0000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c0a50e1000)
~~~

**Comment by rhenium** [comment]
https://github.com/zzak/ruby-openssl-docker/pull/2 should fix this.

**Comment by zzak** [comment]
Thank you everyone, pending [Build #161](https://travis-ci.org/ruby/openssl/builds/136344967).

**Comment by zzak** [comment]
Seems like the `digest/sha2.so` error is fixed but `openssl-1.1.0-pre5` is failing for another reason:

```
ERROR:  Error installing openssl-1.1.0.gem:

	ERROR: Failed to build gem native extension.

    current directory: /opt/ruby/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/openssl-1.1.0/ext/openssl

/opt/ruby/ruby-2.3.1/bin/ruby -r ./siteconf20160609-9-1xvx3je.rb extconf.rb --with-openssl-dir=/opt/openssl/openssl-1.1.0-pre5

checking for t_open() in -lnsl... no

checking for socket() in -lsocket... no

checking for assert.h... yes

checking for openssl/ssl.h... yes

checking for OpenSSL_add_all_digests() in -lcrypto... no

checking for OpenSSL_add_all_digests() in -llibeay32... no

*** extconf.rb failed ***

Could not create Makefile due to some reason, probably lack of necessary

libraries and/or headers.  Check the mkmf.log file for more details.  You may

need configuration options.

Provided configuration options:

	--with-opt-dir

	--without-opt-dir

	--with-opt-include

	--without-opt-include=${opt-dir}/include

	--with-opt-lib

	--without-opt-lib=${opt-dir}/lib

	--with-make-prog

	--without-make-prog

	--srcdir=.

	--curdir

	--ruby=/opt/ruby/ruby-2.3.1/bin/$(RUBY_BASE_NAME)

	--with-openssl-dir

	--with-openssl-include

	--without-openssl-include=${openssl-dir}/include

	--with-openssl-lib

	--without-openssl-lib=${openssl-dir}/lib

	--with-kerberos-dir

	--without-kerberos-dir

	--with-kerberos-include

	--without-kerberos-include=${kerberos-dir}/include

	--with-kerberos-lib

	--without-kerberos-lib=${kerberos-dir}/lib

	--with-broken-apple-openssl

	--without-broken-apple-openssl

	--with-debug

	--without-debug

	--enable-debug

	--disable-debug

	--with-nsllib

	--without-nsllib

	--with-socketlib

	--without-socketlib

	--with-openssl-config

	--without-openssl-config

	--with-pkg-config

	--without-pkg-config

	--with-cryptolib

	--without-cryptolib

	--with-libeay32lib

	--without-libeay32lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/ruby/ruby-2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/openssl-1.1.0/mkmf.log

extconf failed, exit code 1
```

**Comment by rhenium** [comment]
3f037dc1b4717b63ad293356477768a011cb5473 fixed this.

1.1.0-pre5 lacks X509_STORE_{set,get}_ex_data() so it is still failing, though.
https://travis-ci.org/ruby/openssl/jobs/136349286

**Comment by zzak** [comment]
@rhenium Thank you! Let's close this ticket then.
