### ISSUE TITLE
OpenSSL::TestSSLSession#test_ctx_client_session_cb_tls13_exception fails on i686

### ISSUE THREAD

**Issue by voxik** [ruby/openssl#828]
Trying Ruby 3.4 335bba0fde, I am observing following failure on i686:

~~~
OpenSSL::TestSSLSession#test_ctx_client_session_cb_tls13_exception [/builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:290]:
exceptions on 1 threads:
#<Thread:0xf3c80958 /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:247 dead>:
/builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/redhat-linux-build/.ext/common/openssl/buffering.rb:364:in 'OpenSSL::SSL::SSLSocket#syswrite': Connection reset by peer (Errno::ECONNRESET)
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/redhat-linux-build/.ext/common/openssl/buffering.rb:364:in 'OpenSSL::Buffering#do_write'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/redhat-linux-build/.ext/common/openssl/buffering.rb:383:in 'block in OpenSSL::Buffering#write'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/redhat-linux-build/.ext/common/openssl/buffering.rb:382:in 'Array#each'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/redhat-linux-build/.ext/common/openssl/buffering.rb:382:in 'Enumerable#inject'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/redhat-linux-build/.ext/common/openssl/buffering.rb:382:in 'OpenSSL::Buffering#write'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:203:in 'OpenSSL::SSLTestCase#readwrite_loop'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:251:in 'Method#call'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:251:in 'block (4 levels) in OpenSSL::SSLTestCase#start_server'
~~~

This is recently introduced test case as far as I can tell:

https://github.com/ruby/ruby/commit/06fc13a15c72ecf77a638b45ea325d945bc7cc6d

**Comment by rhenium** [comment]
The server side error is expected and should be ignored. #829 should fix it.

**Comment by voxik** [comment]
Thx. But I wonder why i686 only? x86_64, arm64, ppc64le as well as s390x are passing just fine.

**Comment by voxik** [comment]
I could have made some mistake, but the error is still the same even with the patch applied.

**Comment by junaruga** [comment]
Seeing the trace log on the first comment, the `Errno::ECONNRESET` is raised in the `OpenSSL::SSLTestCase#readwrite_loop` in the following line with `server_proc.call(ctx, ssl)`  in `OpenSSL::SSLTestCase#start_server`.

https://github.com/ruby/ruby/blob/335bba0fde0c0407377b6e10050ab6c2ad0d3270/test/openssl/utils.rb#L251

The PR #829 is adding the option `ignore_listener_error: true` to the called `start_server`. However, the option is only to retry `accept_proc.call(ssl)` which is before the `server_proc.call(ctx, ssl)`. So, I don't think the PR #829 can catch the reported error from the `server_proc.call(ctx, ssl)`.

```
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:203:in 'OpenSSL::SSLTestCase#readwrite_loop'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:251:in 'Method#call'
	from /builddir/build/BUILD/ruby-3.4.0_20241219git335bba0fde-build/ruby-3.4.0-335bba0fde/test/openssl/utils.rb:251:in 'block (4 levels) in OpenSSL::SSLTestCase#start_server'
```

**Comment by rhenium** [comment]
You're right. The error happens after the connection is established, for which `ignore_listener_error` has no effect.

@voxik Could you try with the new diff?

**Comment by voxik** [comment]
I have kicked off build here:

https://koji.fedoraproject.org/koji/taskinfo?taskID=127060441

and once done, this will be the i686 build log specifically:

https://kojipkgs.fedoraproject.org//work/tasks/550/127060550/build.log

**Comment by voxik** [comment]
The test has passed 👏

**Comment by rhenium** [comment]
Thanks for checking. I've merged it now.
