### ISSUE TITLE
certificate verify failed (unable to get certificate CRL) (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by bfolkens** [ruby/openssl#949]
The following example fails after installing "OpenSSL 3.6.0":

```ruby
require 'net/http'
require 'uri'

uri = URI('https://example.com')

# Creating a POST request, which is a subclass of Net::HTTPGenericRequest
request = Net::HTTP::Post.new(uri)

# Sending the request
Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
  response = http.request(request)
  puts response.body
end
```

With the following error:

```
/Users/[user]/.local/share/mise/installs/ruby/3.4.6/lib/ruby/3.4.0/net/protocol.rb:46:in 'OpenSSL::SSL::SSLSocket#connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=[2600:1406:5e00:6::17ce:bc12]:443 state=error: certificate verify failed (unable to get certificate CRL) (OpenSSL::SSL::SSLError)
        from /Users/bfolkens/.local/share/mise/installs/ruby/3.4.6/lib/ruby/3.4.0/net/protocol.rb:46:in 'Net::Protocol#ssl_socket_connect'
        from /Users/bfolkens/.local/share/mise/installs/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1736:in 'Net::HTTP#connect'
        from /Users/bfolkens/.local/share/mise/installs/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1636:in 'Net::HTTP#do_start'
        from /Users/bfolkens/.local/share/mise/installs/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1625:in 'Net::HTTP#start'
        from /Users/bfolkens/.local/share/mise/installs/ruby/3.4.6/lib/ruby/3.4.0/net/http.rb:1064:in 'Net::HTTP.start'
        from test.rb:10:in '<main>'
```

`bundle doctor --ssl` fails with:

```
The Gemfile's dependencies are satisfied
Here's your OpenSSL environment:

OpenSSL:       3.3.0
Compiled with: OpenSSL 3.6.0 1 Oct 2025
Loaded with:   OpenSSL 3.6.0 1 Oct 2025

Trying connections to https://rubygems.org:
Bundler:       success
RubyGems:      success
Ruby net/http: failed

Unfortunately, this Ruby can't connect to rubygems.org.

Below affect only Ruby net/http connections:
SSL_CERT_FILE: exists     /opt/homebrew/etc/openssl@3/cert.pem
SSL_CERT_DIR:  exists     /opt/homebrew/etc/openssl@3/certs

Your Ruby can't connect to rubygems.org because you are missing the certificate files OpenSSL needs to verify you are connecting to the genuine rubygems.org servers.

No issues found with the installed bundle
```

**Comment by ledermann** [comment]
Same here. It looks like `DEFAULT_CERT_STORE` is initialized empty, so Ruby cannot verify any SSL connections. I found this temporary workaround:

1. Create `~/.rubyopenssl_default_store.rb`:

   ```ruby
   require "openssl"
   s = OpenSSL::X509::Store.new.tap(&:set_default_paths)
   OpenSSL::SSL::SSLContext.send(:remove_const, :DEFAULT_CERT_STORE) rescue nil
   OpenSSL::SSL::SSLContext.const_set(:DEFAULT_CERT_STORE, s.freeze)
   ```

2. Load it for all Ruby processes, e.g. in your shell config:

   ```sh
   export RUBYOPT="-r$HOME/.rubyopenssl_default_store.rb $RUBYOPT"
   ```

**Comment by rhenium** [comment]
Thanks for your report.

`OpenSSL::SSL::SSLContext#set_params` uses the default cert store with the `OpenSSL::X509::V_FLAG_CRL_CHECK_ALL` flag (and no other flags): https://github.com/ruby/openssl/blob/7f4886bf9943ce8696c4c1535e39016c7c6649d0/lib/openssl/ssl.rb#L92-L94

OpenSSL 3.6.0 appears to have changed the behavior in commit https://github.com/openssl/openssl/commit/b1b4b154fd389ac6254d49cfb11aee36c1c51b84, which doesn't look intentional.

At the same time, ruby/openssl shouldn't set that flag by default. It previously had no effect, according to the man page for `X509_VERIFY_PARAM_set_flags()`:

> X509_V_FLAG_CRL_CHECK_ALL expands CRL checking to the entire certificate chain if X509_V_FLAG_CRL_CHECK has also been enabled, and is otherwise ignored.

**Comment by bfolkens** [comment]
> Same here. It looks like `DEFAULT_CERT_STORE` is initialized empty, so Ruby cannot verify any SSL connections. I found this temporary workaround:
> 
> 1. Create `~/.rubyopenssl_default_store.rb`:
>    require "openssl"
>    s = OpenSSL::X509::Store.new.tap(&:set_default_paths)
>    OpenSSL::SSL::SSLContext.send(:remove_const, :DEFAULT_CERT_STORE) rescue nil
>    OpenSSL::SSL::SSLContext.const_set(:DEFAULT_CERT_STORE, s.freeze)
> 2. Load it for all Ruby processes, e.g. in your shell config:
>    export RUBYOPT="-r$HOME/.rubyopenssl_default_store.rb $RUBYOPT"

Thank you @ledermann !! this worked

Thanks @rhenium for digging into this

**Comment by miharekar** [comment]
Thanks @rhenium 🙏

**Comment by rhenium** [comment]
I've pushed v3.1.2, v3.2.2, and v3.3.1 to rubygems.org with the change in #950.

**Comment by bkuhlmann** [comment]
Hey, all. :wave: 

I'm currently using OpenSSL 3.3.1 (latest version release) but still had to apply Ledermann's fix in order for this to work. I'm also using: `OpenSSL 3.6.0 1 Oct 2025 (Library: OpenSSL 3.6.0 1 Oct 2025)`. I was under the impression that 3.3.1 fixed this but maybe not?

**Comment by okjuan** [comment]
@rhenium how do I consume your fix? My Jekyll site build is still failing. I tried updating the Ruby version from 3.2.0 to 3.2.2 and then to 3.3.0 but I keep getting the same error:
- [Failure on Ruby 3.2.2](https://github.com/okjuan/vbook/actions/runs/18807179969/job/53663039223)
- [Failure on Ruby 3.3.0](https://github.com/okjuan/vbook/actions/runs/18807428289/job/53663637554)

**Comment by jwhitcraft** [comment]
This was fixed in openssl yesterday (12/11/25) but not released yet: https://github.com/openssl/openssl/commit/996d50da8fac4938fd910af96389c1e67ff1cb11
